In [84]:
import pandas as pd
pd.set_option('display.max_rows',20)
df = pd.read_csv(r'D:\github\python-noob\数据分析\data.csv',encoding='utf-8',index_col=0)
#缺失值处理
df.isnull()   #判断是否有缺失值
#删除缺失值
df.dropna(inplace=True)  #删除有缺失值的行
df.dropna(axis=1)  #删除有缺失值的列
# 填充缺失值 
df.fillna(99999) #填充缺失值
df.ffill()        #用上一行数据填充缺失值
df.bfill()          #用下一行数据填充缺失值

                 姓名     年龄       工资        参加时间
工号
1          John Doe   25.0  50000.0  2020-01-15
2      Grace Wilson   30.0  60000.0  2020-02-20
3       Bob Johnson   45.0  75000.0  2019/11/01
6         David Lee  -28.0  48000.0  2022-05-30
8      Frank Miller  -10.0  70000.0  2021-12-05
9      Grace Wilson   40.0  90000.0  2019-04-18
10      Henry Moore   29.0  51000.0  2023-01-25
1          John Doe   25.0  50000.0  2020-01-15
11       Ivy Taylor   33.0  65000.0  2020-06-14
12    Jack Anderson   48.0  72000.0  2017-08-09
..              ...    ...      ...         ...
26        Xena Hill   24.0  44000.0  2022-09-18
27       Yves Scott   39.0  63000.0  2021-01-29
28        Zoe Adams   42.0  69000.0  2019-12-02
29      Aaron Baker   37.0  58000.0  2020-04-26
30      Bella Evans   33.0  64000.0  2023-07-14
31     Carter Green   29.0  52000.0  2022-11-09
32     Diana Harris   46.0  73000.0  2018-05-23
33    Ethan Collins   28.0  47000.0  2021-08-17
34    Fiona Stewart -200.0  82000.0  2020-10-31
35  George Mitchell   41.0  70000.0  2019-06-19

[32 rows x 4 columns]

In [98]:
#查找重复值
import pandas as pd
pd.set_option('display.max_rows',20)
df = pd.read_csv(r'D:\github\python-noob\数据分析\data.csv',encoding='utf-8')
#查看是否有重复的
df.duplicated()    #查找所有列是否重复
df.duplicated(subset=['ID'])   #查找ID列（索引）是否重复
# #删除重复值
df.drop_duplicates(subset=['ID'],keep='first') #保留第一次出现的
df.drop_duplicates(subset=['ID'],keep='last') #保留最后一次出现的

    ID               姓名     年龄       工资        参加时间
1    2     Grace Wilson   30.0  60000.0  2020-02-20
2    3      Bob Johnson   45.0  75000.0  2019/11/01
3    4   Alice Williams    NaN  62000.0  2021-03-10
5    6        David Lee  -28.0  48000.0  2022-05-30
6    7       Emma Davis   35.0      NaN  2020-09-12
7    8     Frank Miller  -10.0  70000.0  2021-12-05
8    9     Grace Wilson   40.0  90000.0  2019-04-18
9   10      Henry Moore   29.0  51000.0  2023-01-25
10   1         John Doe   25.0  50000.0  2020-01-15
11  11       Ivy Taylor   33.0  65000.0  2020-06-14
..  ..              ...    ...      ...         ...
26  26        Xena Hill   24.0  44000.0  2022-09-18
27  27       Yves Scott   39.0  63000.0  2021-01-29
28  28        Zoe Adams   42.0  69000.0  2019-12-02
29  29      Aaron Baker   37.0  58000.0  2020-04-26
30  30      Bella Evans   33.0  64000.0  2023-07-14
31  31     Carter Green   29.0  52000.0  2022-11-09
32  32     Diana Harris   46.0  73000.0  2018-05-23
33  33    Ethan Collins   28.0  47000.0  2021-08-17
34  34    Fiona Stewart -200.0  82000.0  2020-10-31
35  35  George Mitchell   41.0  70000.0  2019-06-19

[34 rows x 5 columns]

In [142]:
#处理异常值
import pandas as pd
pd.set_option('display.max_rows',20)
df = pd.read_csv(r'D:\github\python-noob\数据分析\data.csv',encoding='utf-8')
df[(df['年龄'] < 0) | (df['工资'] < 0)] #查看异常值
df[(df['年龄'] < 0) | (df['工资'] < 0)].index #查看异常值的索引
#删除异常值
# df.drop(df[(df['年龄'] < 0) | (df['工资'] < 0)].index)
#修复异常值
# df['工资']=df['工资'].abs()
# df['年龄']=df['年龄'].abs()
df[['工资','年龄']] = df[['工资','年龄']].abs() #将两列的数据取绝对值
df

    ID               姓名    年龄       工资        参加时间
0    1         John Doe  25.0  50000.0  2020-01-15
1    2     Grace Wilson  30.0  60000.0  2020-02-20
2    3      Bob Johnson  45.0  75000.0  2019/11/01
3    4   Alice Williams   NaN  62000.0  2021-03-10
4    1    Charlie Brown  52.0      NaN  2018-07-22
5    6        David Lee  28.0  48000.0  2022-05-30
6    7       Emma Davis  35.0      NaN  2020-09-12
7    8     Frank Miller  10.0  70000.0  2021-12-05
8    9     Grace Wilson  40.0  90000.0  2019-04-18
9   10      Henry Moore  29.0  51000.0  2023-01-25
..  ..              ...   ...      ...         ...
26  26        Xena Hill  24.0  44000.0  2022-09-18
27  27       Yves Scott  39.0  63000.0  2021-01-29
28  28        Zoe Adams  42.0  69000.0  2019-12-02
29  29      Aaron Baker  37.0  58000.0  2020-04-26
30  30      Bella Evans  33.0  64000.0  2023-07-14
31  31     Carter Green  29.0  52000.0  2022-11-09
32  32     Diana Harris  46.0  73000.0  2018-05-23
33  33    Ethan Collins  28.0  47000.0  2021-08-17
34  34    Fiona Stewart  20.0  82000.0  2020-10-31
35  35  George Mitchell  41.0  70000.0  2019-06-19

[36 rows x 5 columns]

In [137]:
#数据格式转换
import pandas as pd
pd.set_option('display.max_rows',20)
df = pd.read_csv(r'D:\github\python-noob\数据分析\data.csv',encoding='utf-8')
df['参加时间'] = df['参加时间'].str.replace('/','-') #替换/为-,用str.replace可以直接用原始字符串直接转换
df

    ID               姓名    年龄       工资        参加时间
0    1         John Doe  25.0  50000.0  2020-01-15
1    2     Grace Wilson  30.0 -60000.0  2020-02-20
2    3      Bob Johnson  45.0  75000.0  2019-11-01
3    4   Alice Williams   NaN  62000.0  2021-03-10
4    1    Charlie Brown  52.0      NaN  2018-07-22
5    6        David Lee -28.0  48000.0  2022-05-30
6    7       Emma Davis  35.0      NaN  2020-09-12
7    8     Frank Miller -10.0  70000.0  2021-12-05
8    9     Grace Wilson  40.0  90000.0  2019-04-18
9   10      Henry Moore  29.0  51000.0  2023-01-25
..  ..              ...   ...      ...         ...
26  26        Xena Hill  24.0  44000.0  2022-09-18
27  27       Yves Scott  39.0  63000.0  2021-01-29
28  28        Zoe Adams  42.0  69000.0  2019-12-02
29  29      Aaron Baker  37.0  58000.0  2020-04-26
30  30      Bella Evans  33.0  64000.0  2023-07-14
31  31     Carter Green  29.0  52000.0  2022-11-09
32  32     Diana Harris  46.0  73000.0  2018-05-23
33  33    Ethan Collins  28.0  47000.0  2021-08-17
34  34    Fiona Stewart -20.0  82000.0  2020-10-31
35  35  George Mitchell  41.0  70000.0  2019-06-19

[36 rows x 5 columns]